todo:
    keyword: ["@todo", "TODO", "TODO:"]
    autoAssign: true
    bodyKeyword: ["@body", "BODY"]
    blobLines: 10
    caseSensitive: false
    label: ["todo", "bot"]
    reopenClosed: true
