backend:
  name: github
  repo: ChrisChinchilla/chrischinchilla.com # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow
media_folder: "images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "posts" # Used in routes, e.g. /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    filter:
      - field: publication_url
      - value: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publication URL", name: "publication_url", widget: "string", required: false}
  - name: "clients" # Used in routes, e.g. /admin/collections/blog
    label: "Clients" # Used in the UI
    folder: "_clients" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "select", options: ["Blogging", "Technical writing"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Chris", "Cate", "Both"]}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Company URL", name: "company_url", widget: "string"}
      - {label: "Start Date", name: "start_date", widget: "date",  format: "YY-MM-DD"}
      - {label: "End Date", name: "end_date", widget: "date",  format: "YY-MM-DD"}
  - name: "events" # Used in routes, e.g. /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{event}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Action", name: "action", widget: "select", options: ["to hear about", "to speak about"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event", name: "event", widget: "string"}
      - {label: "Event", name: "layout", widget: "hidden", default: "event"}
      - {label: "Venue", name: "venue", widget: "string"}
      - {label: "Categories", name: "categories", widget: "select", options: ["Chris", "Cate", "Both"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Event URL", name: "pre_url", widget: "string"}
      - {label: "Presentation source", name: "pre_source", widget: "string", required: false}
      - {label: "Start Date", name: "start_date", widget: "date",  format: "YY-MM-DD"}
      - {label: "End Date", name: "end_date", widget: "date",  format: "YY-MM-DD"}
